# -*- coding: utf-8 -*-
"""HW2_Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gYWlvtz5PKwwAWWUo-dcORf_eSuD5pff
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
import joblib

df = pd.read_csv("DatosHW2.csv")


X = df.iloc[:, 2].values.reshape(-1, 1)  # Water % (Target)
y = df.iloc[:, 4].values                 # Voltage

# ======================
# Polynomial Regression
# ======================
poly = PolynomialFeatures(degree=4)  # try degree=2,3
X_poly = poly.fit_transform(X)

model = LinearRegression()
model.fit(X_poly, y)

# ======================
# Plot calibration curve
# ======================
plt.figure(figsize=(8,5))
plt.scatter(X, y, label="Measured Data", color="blue")

X_fit = np.linspace(X.min(), X.max(), 200).reshape(-1, 1)
y_fit = model.predict(poly.transform(X_fit))

plt.plot(X_fit, y_fit, color="red", linewidth=2, label="Fitted Curve")
plt.xlabel("Water Content (%)")
plt.ylabel("Voltage (V)")
plt.title("Soil/Sand Moisture Sensor Calibration")
plt.legend()
plt.grid(True)
plt.show()

# ======================
# Export coefficients
# ======================
print("Polynomial coefficients:", model.coef_)
print("Intercept:", model.intercept_)

# Save model for later use
joblib.dump((poly, model), "moisture_calibration.pkl")
print("✅ Calibration model saved as moisture_calibration.pkl")