# -*- coding: utf-8 -*-
"""Micro_poly.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1be6rIAuMVePiJocbFcbTakehVHnTwO8b
"""

!pip install sympy
!pip install numpy

import sympy as sp
import numpy as np

"""FORMA CORRECTA"""

# --- define polynomial (as you provided) ---
x = sp.Symbol('x')
poly = 171.8818*x**3 - 3.5877972*x**2 + 0.03244289*x - 0.000107575758

# LUT settings
lut_size = 4096  # 0..4095 ADC for ESP32 12-bit

# --- fast numeric evaluation with numpy ---
poly_func = sp.lambdify(x, poly, "numpy")
xs = np.arange(lut_size, dtype=np.float64)
raw_vals = poly_func(xs).astype(np.float64)  # may contain large numbers

# Protect against NaN/inf produced by the polynomial (if any)
raw_vals = np.nan_to_num(raw_vals, nan=0.0, posinf=np.finfo(np.float64).max, neginf=0.0)

# Use raw_vals.max() as the 100% reference (as you requested)
max_raw = float(raw_vals.max())
print(f"Debug: raw max = {max_raw}")

# Avoid division by zero if max_raw is 0 or negative (fallback)
if max_raw <= 0:
    # fallback: use peak-to-peak or set max_raw = 1 to avoid div-by-zero
    peak = float(raw_vals.ptp())
    max_raw = peak if peak > 0 else 1.0
    print(f"Warning: max_raw non-positive; using fallback max_raw = {max_raw}")

# Linear scale: 0 -> 0, max_raw -> 100
scaled = np.round((raw_vals / max_raw) * 100.0).astype(int)

# Enforce strict 0..100 bounds
scaled = np.clip(scaled, 0, 100)

# Optional: force index 0 to be exactly 0%
scaled[0] = 0

# --- write the C header file ---
with open("lookuptable.h", "w") as f:
    f.write("#ifndef LOOKUPTABLE_H\n")
    f.write("#define LOOKUPTABLE_H\n\n")
    f.write(f"#define LUT_SIZE {lut_size}\n")
    f.write("static const int lookup_table[LUT_SIZE] = {\n")

    for i, val in enumerate(scaled):
        # add trailing comma except maybe last (C allows trailing comma though)
        if (i + 1) % 8 == 0:
            f.write(f"  {int(val)},\n")
        else:
            f.write(f"  {int(val)},")
    f.write("\n};\n\n")
    f.write("#endif // LOOKUPTABLE_H\n")

print("✅ lookuptable.h generated (values 0..100)")

"""DA LOOKUP TABLE MAL

"""

x = sp.Symbol('x')
poly = 171.8818*x**3 - 3.5877972*x**2 + 0.03244289*x - 0.000107575758


lut_size = 4096


lookup = [max(0, min(100, int(poly.subs(x, i)))) for i in range(lut_size)]

# Generate lookup table in C header
with open("lookuptable.h", "w") as f:
    f.write("#ifndef LOOKUPTABLE_H\n")
    f.write("#define LOOKUPTABLE_H\n\n")
    f.write(f"#define LUT_SIZE {lut_size}\n")
    f.write("static const int lookup_table[LUT_SIZE] = {\n")

    for i, val in enumerate(lookup):
        f.write(f"  {val},")
        if (i + 1) % 8 == 0:  # format 8 values per line
            f.write("\n")
    f.write("\n};\n\n")
    f.write("#endif // LOOKUPTABLE_H\n")

print("✅ Lookup table generated: lookuptable.h")

#x=sp.Symbol('x')
#poly = 171.8818*x**3-3.5877972*x**2+0.03244289*x-.000107575758
#f=sp.lambdify(x,poly,"numpy")
#display(poly)

#lut_size = 4096
#lookup = [ int ( poly . subs (x , i ) ) for i in range ( lut_size ) ]


#display(lookup)

#with open("lookuptable.h", "w") as f:
 #   f.write("#ifndef LOOKUPTABLE_H\n")
  #  f.write("#define LOOKUPTABLE_H\n\n")
   # f.write(f"#define LUT_SIZE {lut_size}\n")
   # f.write("static const int lookup_table[LUT_SIZE] = {\n")

    #for i, val in enumerate(lookup):
     #   f.write(f"  {val},")
      #  if (i + 1) % 8 == 0:  # format 8 values per line
       #     f.write("\n")
    #f.write("\n};\n\n")
    #f.write("#endif // LOOKUPTABLE_H\n")

#print("✅ Lookup table generated: lookuptable.h")

